[package]
name = "vst-exploration"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*", "xtask"]

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"